publishing:
  email:
    recipients:
      - me123tail@wp.pl

workflows:
  android-release:
    name: Android Release APK
    max_build_duration: 30
    instance_type: mac_mini_m2
    working_directory: szlaban
    scripts:
      - name: Build Android Release APK
        script: |
          # 1. Wejdź do katalogu głównego kodu Androida (tam gdzie jest build.gradle.kts)
          if [ -d "app" ]; then
            cd app
          fi
          
          echo "Aktualna ścieżka: $(pwd)"
          
          # 2. Generowanie brakujących plików wrapper (gradlew) za pomocą systemowego polecenia
          echo "Generuję brakujące pliki uruchomieniowe gradlew..."
          gradle wrapper
          
          # 3. Nadanie uprawnień i natychmiastowe uruchomienie kompilacji APK
          echo "Uruchamiam kompilację APK..."
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - "**/build/outputs/apk/release/*.apk"
