publishing:
  email:
    recipients:
      - me123tail@wp.pl

workflows:
  android-release:
    name: Android Release APK
    max_build_duration: 30
    instance_type: mac_mini_m2
    working_directory: szlaban
    scripts:
      - name: Build Android Release APK
        script: |
          # 1. Tworzenie wymaganego pliku .env.example, aby Gradle nie wyrzucał błędu
          echo "Tworzę plik .env.example..."
          touch .env.example
          
          # 2. Wejdź do katalogu kodu Androida
          if [ -d "app" ]; then
            cd app
          fi
          
          # 3. Generowanie plików wrapper
          echo "Generuję pliki uruchomieniowe gradlew..."
          gradle wrapper
          
          # 4. Uruchomienie kompilacji APK
          echo "Uruchamiam kompilację APK..."
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - "**/build/outputs/apk/release/*.apk"
